<?php

return [
    'workplaces' => [
        // الإدارات والأقسام — من كشف موظفي الإدارة العامة
        'training_development' => 'إدارة التدريب والتطوير',
        'services_dept' => 'إدارة الخدمات',
        'investments_control' => 'إدارة الرقابة على الاستثمارات',
        'public_companies_control' => 'إدارة الرقابة على الشركات العامة',
        'banking_control' => 'إدارة الرقابة على القطاع المصرفي',
        'admin_affairs_dept' => 'إدارة الشؤون الإدارية',
        'public_activity' => 'إدارة النشاط العام',
        'staff_affairs' => 'إدارة شؤون العاملين',
        'regional_companies_control' => 'ادارة الرقابة على الشركات بالمناطق',
        'regional_institutions_control' => 'ادارة الرقابة على الهيئات و المؤسسات بالمناطق',
        'justice_security_defense_control' => 'ادارة الرقابة على قطاعات العدل و الامن و الدفاع',
        'health_sector_control' => 'ادارة الرقابة على قطاعالصحي',
        'regional_services_control' => 'ادارة الرقابة على مراقبات الخدمات بالمناطق',
        'local_gov_municipalities_control' => 'ادارة الرقابة على وزارة الحكم المحلي و البلديات',
        'state_projects_assets_control' => 'ادارة الرقابة علي مشروعات الدولة ومتابعة الاصول',
        'payments_review' => 'ادارة مراجعة الدفعات',
        'security' => 'الأمن',
        'general_admin_services' => 'الإدارة العامة للشؤون الادارية والخدمات',
        'sovereign_financial_control' => 'الادارة العامة للرقابة المالية على القطاع السيادي',
        'investments_banks_control' => 'الادارة العامة للرقابة على الاستثمارات والمصارف',
        'service_sectors_control' => 'الادارة العامة للرقابة على القطاعات الخدمية',
        'local_gov_control' => 'الادارة العامة للرقابة على قطاع الحكم المحلي',
        'state_projects_payments_control' => 'الادارة العامة للرقابة على مشروعات الدولة ومراجعة الدفعات',
        'energy_public_companies_control' => 'الادارة العامة للرقابة علي قطاعي الطاقة والشركات العامة',
        'financial_affairs' => 'الادارة العامة للشؤون المالية',
        'hr_general' => 'الادارة العامة للموارد البشرية',
        'transport' => 'الحركة',
        'services_maintenance' => 'الخدمات و الصيانة',
        'public_relations' => 'العلاقات العامة',
        'archives' => 'المحفوظات',
        'assets_section' => 'قسم الأصول',
        'rest_house_section' => 'قسم الإستراحة',
        'programming_apps_section' => 'قسم البرمجة والتطبيقات الالكترونية',
        'legislation_cases_section' => 'قسم التشريعات والقضايا',
        'institutional_development_section' => 'قسم التطوير المؤسسي',
        'reports_section' => 'قسم التقارير',
        'technical_support_section' => 'قسم الدعم الفني',
        'legal_affairs_section' => 'قسم الشؤون القانونية',
        'networks_comms_section' => 'قسم الشبكات والاتصالات',
        'maintenance_tech_support_section' => 'قسم الصيانة والدعم التقني',
        'payments_section' => 'قسم المدفوعات',
        'payroll_section' => 'قسم المرتبات',
        'budget_section' => 'قسم الميزانية',
        'info_security_section' => 'قسم امن المعلومات',
        'afrosai_presidency_section' => 'قسم يتولى مهام رئاسة الأفروساي',
        'research_center' => 'مركز البحوث والدراسات',
        'comms_office' => 'مكتب الاتصال والتواصل',
        'planning_reports_office' => 'مكتب التخطيط واعداد التقارير',
        'intl_coop_office' => 'مكتب التعاون الدولي',
        'inspection_followup_office' => 'مكتب التفتيش والمتابعة',
        'state_assets_control_office' => 'مكتب الرقابة على اصول وممتلكات الدولة',
        'performance_control_office' => 'مكتب الرقابة على الاداء',
        'contracts_control_office' => 'مكتب الرقابة علي العقود',
        'legal_office' => 'مكتب الشؤون القانونية',
        'financial_violations_office' => 'مكتب المخالفات المالية',
        'internal_audit_office' => 'مكتب المراجعة الداخلية',
        'info_office' => 'مكتب المعلومات',
        'it_office' => 'مكتب تقنية المعلومات',
        'bureau_chief_office' => 'مكتب رئيس الديوان',
        'quality_assurance_office' => 'مكتب ضمان الجودة',
        'financial_statements_review_office' => 'مكتب مراجعة القوائم والتقارير المالية',
        'bureau_deputy' => 'وكيل الديوان',

        // الفروع — من كشف موظفي الفروع
        'al_asabaa' => 'الاصابعة',
        'al_jufra' => 'الجفرة',
        'al_jamil' => 'الجميل',
        'al_zawiya' => 'الزاوية',
        'al_zintan' => 'الزنتان',
        'al_ajaylat' => 'العجيلات',
        'al_murqub' => 'المرقب',
        'batin_al_jabal' => 'باطن الجبل',
        'tarhuna' => 'ترهونة',
        'jado' => 'جادو',
        'zliten' => 'زليتن',
        'zuwara' => 'زوارة',
        'sebha' => 'سبها',
        'sabratha_sorman' => 'صبراته / صرمان',
        'tripoli' => 'طرابلس',
        'ghat' => 'غات',
        'ghadames' => 'غدامس',
        'west_south_tripoli' => 'غرب جنوب طرابلس',
        'gharyan' => 'غريان',
        'bani_walid' => 'فرع بني وليد',
        'murzuq' => 'مرزق',
        'mizda' => 'مزدة',
        'msallata' => 'مسلاته',
        'misrata' => 'مصراته',
        'nalut' => 'نالوت',
        'al_shati' => 'وادى الشاطئ',
        'wadi_al_hayat' => 'وادي الاجال',
    ],

    'job_titles' => [
        'employee' => 'موظف',
        'leader' => 'قيادي',
    ],

    'cities' => [
        // مدن / فروع الديوان
        'al_asabaa' => 'الاصابعة',
        'al_jufra' => 'الجفرة',
        'al_jamil' => 'الجميل',
        'al_zawiya' => 'الزاوية',
        'al_zintan' => 'الزنتان',
        'al_ajaylat' => 'العجيلات',
        'al_murqub' => 'المرقب',
        'batin_al_jabal' => 'باطن الجبل',
        'tarhuna' => 'ترهونة',
        'jado' => 'جادو',
        'zliten' => 'زليتن',
        'zuwara' => 'زوارة',
        'sebha' => 'سبها',
        'sabratha_sorman' => 'صبراته / صرمان',
        'tripoli' => 'طرابلس',
        'ghat' => 'غات',
        'ghadames' => 'غدامس',
        'west_south_tripoli' => 'غرب جنوب طرابلس',
        'gharyan' => 'غريان',
        'bani_walid' => 'فرع بني وليد',
        'murzuq' => 'مرزق',
        'mizda' => 'مزدة',
        'msallata' => 'مسلاته',
        'misrata' => 'مصراته',
        'nalut' => 'نالوت',
        'al_shati' => 'وادى الشاطئ',
        'wadi_al_hayat' => 'وادي الاجال',
    ],

    /*
    |--------------------------------------------------------------------------
    | Upload limits
    |--------------------------------------------------------------------------
    |
    | Max image size for registration photos (employee + beneficiaries).
    | Value is in kilobytes. Keep in sync with config/livewire.php
    | temporary_file_upload.rules max value.
    |
    */
    'max_upload_kilobytes' => 10240,

    /*
    |--------------------------------------------------------------------------
    | Nationalities available when spouse/mother is not Libyan.
    | Libya itself is selected via the "ليبي؟" toggle, not this list.
    |
    | nationality_priority: shown first (neighbors / common in Libya), then A–Z, then أخرى.
    */
    'nationality_priority' => [
        'egyptian',
        'tunisian',
        'algerian',
        'moroccan',
        'sudanese',
        'chadian',
        'nigerien',
        'palestinian',
        'syrian',
        'lebanese',
        'jordanian',
        'saudi',
        'emirati',
        'kuwaiti',
        'qatari',
        'bahraini',
        'omani',
        'yemeni',
        'iraqi',
        'turkish',
        'eritrean',
        'somali',
        'ethiopian',
    ],

    'nationalities' => [
        'afghan' => 'أفغانستان',
        'albanian' => 'ألبانيا',
        'algerian' => 'الجزائر',
        'american' => 'الولايات المتحدة',
        'argentine' => 'الأرجنتين',
        'armenian' => 'أرمينيا',
        'australian' => 'أستراليا',
        'austrian' => 'النمسا',
        'azerbaijani' => 'أذربيجان',
        'bahraini' => 'البحرين',
        'bangladeshi' => 'بنغلاديش',
        'belarusian' => 'بيلاروسيا',
        'belgian' => 'بلجيكا',
        'beninese' => 'بنين',
        'bosnian' => 'البوسنة والهرسك',
        'brazilian' => 'البرازيل',
        'british' => 'المملكة المتحدة',
        'bulgarian' => 'بلغاريا',
        'burkinabe' => 'بوركينا فاسو',
        'cameroonian' => 'الكاميرون',
        'canadian' => 'كندا',
        'chadian' => 'تشاد',
        'chinese' => 'الصين',
        'comorian' => 'جزر القمر',
        'congolese' => 'الكونغو',
        'croatian' => 'كرواتيا',
        'cypriot' => 'قبرص',
        'czech' => 'التشيك',
        'danish' => 'الدنمارك',
        'djiboutian' => 'جيبوتي',
        'dutch' => 'هولندا',
        'egyptian' => 'مصر',
        'emirati' => 'الإمارات',
        'eritrean' => 'إريتريا',
        'estonian' => 'إستونيا',
        'ethiopian' => 'إثيوبيا',
        'filipino' => 'الفلبين',
        'finnish' => 'فنلندا',
        'french' => 'فرنسا',
        'gabonese' => 'الغابون',
        'gambian' => 'غامبيا',
        'georgian' => 'جورجيا',
        'german' => 'ألمانيا',
        'ghanaian' => 'غانا',
        'greek' => 'اليونان',
        'guinean' => 'غينيا',
        'hungarian' => 'المجر',
        'icelandic' => 'آيسلندا',
        'indian' => 'الهند',
        'indonesian' => 'إندونيسيا',
        'iranian' => 'إيران',
        'iraqi' => 'العراق',
        'irish' => 'أيرلندا',
        'italian' => 'إيطاليا',
        'ivorian' => 'ساحل العاج',
        'japanese' => 'اليابان',
        'jordanian' => 'الأردن',
        'kazakh' => 'كازاخستان',
        'kenyan' => 'كينيا',
        'korean' => 'كوريا الجنوبية',
        'kuwaiti' => 'الكويت',
        'kyrgyz' => 'قيرغيزستان',
        'latvian' => 'لاتفيا',
        'lebanese' => 'لبنان',
        'lithuanian' => 'ليتوانيا',
        'luxembourgish' => 'لوكسمبورغ',
        'malaysian' => 'ماليزيا',
        'malian' => 'مالي',
        'maltese' => 'مالطا',
        'mauritanian' => 'موريتانيا',
        'mexican' => 'المكسيك',
        'moldovan' => 'مولدوفا',
        'montenegrin' => 'الجبل الأسود',
        'moroccan' => 'المغرب',
        'nigerian' => 'نيجيريا',
        'nigerien' => 'النيجر',
        'norwegian' => 'النرويج',
        'omani' => 'عُمان',
        'pakistani' => 'باكستان',
        'palestinian' => 'فلسطين',
        'polish' => 'بولندا',
        'portuguese' => 'البرتغال',
        'qatari' => 'قطر',
        'romanian' => 'رومانيا',
        'russian' => 'روسيا',
        'rwandan' => 'رواندا',
        'saudi' => 'السعودية',
        'senegalese' => 'السنغال',
        'serbian' => 'صربيا',
        'singaporean' => 'سنغافورة',
        'slovak' => 'سلوفاكيا',
        'slovenian' => 'سلوفينيا',
        'somali' => 'الصومال',
        'south_african' => 'جنوب أفريقيا',
        'spanish' => 'إسبانيا',
        'sri_lankan' => 'سريلانكا',
        'sudanese' => 'السودان',
        'swedish' => 'السويد',
        'swiss' => 'سويسرا',
        'syrian' => 'سوريا',
        'tajik' => 'طاجيكستان',
        'tanzanian' => 'تنزانيا',
        'thai' => 'تايلاند',
        'togolese' => 'توغو',
        'tunisian' => 'تونس',
        'turkish' => 'تركيا',
        'turkmen' => 'تركمانستان',
        'ugandan' => 'أوغندا',
        'ukrainian' => 'أوكرانيا',
        'uzbek' => 'أوزبكستان',
        'venezuelan' => 'فنزويلا',
        'vietnamese' => 'فيتنام',
        'yemeni' => 'اليمن',
        'other' => 'أخرى',
    ],

    'chronic_conditions' => [
        'diabetes' => 'السكري',
        'hypertension' => 'ارتفاع ضغط الدم',
        'heart_disease' => 'أمراض القلب والشرايين',
        'asthma' => 'الربو',
        'copd' => 'الانسداد الرئوي',
        'chronic_kidney_disease' => 'أمراض الكلى المزمنة',
        'cancer' => 'السرطان',
        'chronic_joint_disease' => 'أمراض المفاصل المزمنة',
        'chronic_neurological_disease' => 'الأمراض العصبية المزمنة',
        'chronic_autoimmune_disease' => 'الأمراض المناعية المزمنة',
        'hypothyroidism' => 'خمول الغدة الدرقية',
    ],
];
